<a href="https://colab.research.google.com/github/Arhanabdullah/College-ML-Assignment/blob/main/Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
 import numpy as np

arr = np.arange(1, 11)

print("Array:", arr)
print("Shape:", arr.shape)
print("Data Type:", arr.dtype)
print("Sum of elements:", arr.sum())
print("Mean:", arr.mean())
print("Maximum value:", arr.max())
print("Minimum value:", arr.min())

Array: [ 1  2  3  4  5  6  7  8  9 10]
Shape: (10,)
Data Type: int64
Sum of elements: 55
Mean: 5.5
Maximum value: 10
Minimum value: 1


In [2]:
import numpy as np

# Create two 3x3 matrices
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nMatrix Addition:")
print(A + B)

print("\nMatrix Subtraction:")
print(A - B)

print("\nElement-wise Multiplication:")
print(A * B)

print("\nMatrix Multiplication:")
print(A @ B)

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Matrix Addition:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Matrix Subtraction:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

Element-wise Multiplication:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Matrix Multiplication:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [3]:
import numpy as np

marks = np.array([
    [80, 75, 90, 85],
    [70, 88, 76, 82],
    [92, 95, 89, 90],
    [65, 72, 68, 75],
    [85, 80, 78, 88]
])

print("Marks:")
print(marks)

student_avg = np.mean(marks, axis=1)
print("\nAverage marks of each student:")
print(student_avg)

subject_avg = np.mean(marks, axis=0)
print("\nAverage marks of each subject:")
print(subject_avg)

print("\nHighest marks:", np.max(marks))

print("Lowest marks:", np.min(marks))

student_total = np.sum(marks, axis=1)
print("\nTotal marks of each student:")
print(student_total)

highest_student = np.argmax(student_total)
print("\nStudent having highest total marks: Student", highest_student + 1)
print("Highest total marks:", student_total[highest_student])

Marks:
[[80 75 90 85]
 [70 88 76 82]
 [92 95 89 90]
 [65 72 68 75]
 [85 80 78 88]]

Average marks of each student:
[82.5  79.   91.5  70.   82.75]

Average marks of each subject:
[78.4 82.  80.2 84. ]

Highest marks: 95
Lowest marks: 65

Total marks of each student:
[330 316 366 280 331]

Student having highest total marks: Student 3
Highest total marks: 366


In [4]:
import numpy as np

image = np.array([
    [50, 100, 150],
    [200, 220, 240],
    [100, 180, 255]
])

print("Original Image:")
print(image)

normalized = image / 255
print("\nNormalized Image:")
print(normalized)

bright_image = image + 30
print("\nAfter Increasing Brightness:")
print(bright_image)

clipped_image = np.clip(bright_image, 0, 255)
print("\nAfter Clipping:")
print(clipped_image)

avg_intensity = np.mean(clipped_image)
print("\nAverage Pixel Intensity:", avg_intensity)

Original Image:
[[ 50 100 150]
 [200 220 240]
 [100 180 255]]

Normalized Image:
[[0.19607843 0.39215686 0.58823529]
 [0.78431373 0.8627451  0.94117647]
 [0.39215686 0.70588235 1.        ]]

After Increasing Brightness:
[[ 80 130 180]
 [230 250 270]
 [130 210 285]]

After Clipping:
[[ 80 130 180]
 [230 250 255]
 [130 210 255]]

Average Pixel Intensity: 191.11111111111111


In [5]:
import numpy as np

sales = np.array([
    [100, 120, 150, 130],
    [110, 125, 160, 140],
    [105, 115, 155, 135],
    [120, 130, 170, 145],
    [125, 135, 180, 150],
    [130, 140, 190, 160]
])

print("Sales Data:")
print(sales)

total_sales = np.sum(sales, axis=0)
print("\nTotal sales of each product:")
print(total_sales)

avg_sales = np.mean(sales, axis=0)
print("\nAverage monthly sales of each product:")
print(avg_sales)

best_product = np.argmax(total_sales)
print("\nBest selling product: Product", best_product + 1)

monthly_total = np.sum(sales, axis=1)
best_month = np.argmax(monthly_total)
print("\nMonth with highest overall sales: Month", best_month + 1)
print("Total sales in that month:", monthly_total[best_month])

std_sales = np.std(sales, axis=0)
print("\nStandard deviation of each product:")
print(std_sales)

Sales Data:
[[100 120 150 130]
 [110 125 160 140]
 [105 115 155 135]
 [120 130 170 145]
 [125 135 180 150]
 [130 140 190 160]]

Total sales of each product:
[ 690  765 1005  860]

Average monthly sales of each product:
[115.         127.5        167.5        143.33333333]

Best selling product: Product 3

Month with highest overall sales: Month 6
Total sales in that month: 620

Standard deviation of each product:
[10.8012345   8.53912564 14.06828585  9.86013297]
